import type { DunkType } from '@/types'

export const ALL_DUNKS: DunkType[] = [
  {
    id: 'basic_two',
    name: '양손 덩크',
    nameEn: 'Two-Hand Dunk',
    difficulty: 1,
    description: '양손으로 공을 잡고 힘차게 내리꽂는 가장 기본적인 덩크슛. 모든 덩크의 시작.',
    controls: 'SPACE',
    unlockCondition: '기본 해제',
    requiredVertical: 70,
    unlocked: true,
    icon: '🏀',
    famous: 'LeBron James의 힘 폭발 덩크',
    category: 'basic'
  },
  {
    id: 'basic_one',
    name: '원핸드 덩크',
    nameEn: 'One-Hand Dunk',
    difficulty: 2,
    description: '한 손으로 공을 잡고 팔을 뻗어 꽂는 덩크. 키가 작아도 멋지게 할 수 있다.',
    controls: 'A + SPACE',
    unlockCondition: '양손 덩크 5회',
    requiredVertical: 75,
    unlocked: false,
    icon: '✋',
    famous: 'Michael Jordan의 베이스라인 덩크',
    category: 'basic'
  },
  {
    id: 'reverse',
    name: '리버스 덩크',
    nameEn: 'Reverse Dunk',
    difficulty: 3,
    description: '바스켓을 등지고 점프하여 뒤로 꽂는 덩크. 공중에서의 회전이 핵심.',
    controls: 'S + SPACE',
    unlockCondition: '원핸드 덩크 10회',
    requiredVertical: 80,
    unlocked: false,
    icon: '🔄',
    famous: 'Dominique Wilkins의 리버스 폭격',
    category: 'basic'
  },
  {
    id: 'windmill',
    name: '윈드밀 덩크',
    nameEn: 'Windmill Dunk',
    difficulty: 4,
    description: '공을 아래로 크게 휘두르며 풍차처럼 돌려 꽂는 화려한 덩크.',
    controls: 'D + SPACE',
    unlockCondition: '리버스 덩크 10회',
    requiredVertical: 85,
    unlocked: false,
    icon: '💫',
    famous: 'Dominique Wilkins의 빅 D 윈드밀',
    category: 'acrobatic'
  },
  {
    id: 'three_sixty',
    name: '360도 덩크',
    nameEn: '360 Dunk',
    difficulty: 4,
    description: '공중에서 360도 회전 후 덩크. 순간의 결단력과 공중 감각이 필요.',
    controls: 'A + D + SPACE',
    unlockCondition: '윈드밀 덩크 5회',
    requiredVertical: 88,
    unlocked: false,
    icon: '🌀',
    famous: 'Kobe Bryant의 올스타전 360',
    category: 'acrobatic'
  },
  {
    id: 'between_legs',
    name: '다리 사이 덩크',
    nameEn: 'Between the Legs Dunk',
    difficulty: 5,
    description: '공중에서 두 다리 사이로 공을 통과시켜 꽂는 초고난도 덩크.',
    controls: 'W + S + SPACE',
    unlockCondition: '360도 덩크 3회',
    requiredVertical: 90,
    unlocked: false,
    icon: '🦵',
    famous: 'Vince Carter의 2000 슬램덩크 대회',
    category: 'legendary'
  },
  {
    id: 'alleyoop',
    name: '앨리웁 덩크',
    nameEn: 'Alley-Oop Dunk',
    difficulty: 3,
    description: '파트너가 띄워준 공을 공중에서 받아 꽂는 팀 플레이의 꽃.',
    controls: 'Q + SPACE',
    unlockCondition: '양손 덩크 20회',
    requiredVertical: 80,
    unlocked: false,
    icon: '🤝',
    famous: 'Shaquille O\'Neal + Kobe Bryant 앨리웁 콤보',
    category: 'basic'
  },
  {
    id: 'tomahawk',
    name: '토마호크 덩크',
    nameEn: 'Tomahawk Dunk',
    difficulty: 3,
    description: '공을 머리 위에서 도끼처럼 힘차게 내리꽂는 강력한 덩크.',
    controls: 'W + SPACE',
    unlockCondition: '양손 덩크 15회',
    requiredVertical: 82,
    unlocked: false,
    icon: '🪓',
    famous: 'Blake Griffin의 폭발적인 토마호크',
    category: 'power'
  },
  {
    id: 'cradle',
    name: '크래들 덩크',
    nameEn: 'Cradle Dunk',
    difficulty: 4,
    description: '공을 아기를 안듯이 한쪽 팔꿈치로 감싸며 꽂는 우아한 덩크.',
    controls: 'E + SPACE',
    unlockCondition: '원핸드 덩크 15회',
    requiredVertical: 85,
    unlocked: false,
    icon: '👶',
    famous: 'Julius Erving(Dr. J)의 크래들 덩크',
    category: 'acrobatic'
  },
  {
    id: 'putback',
    name: '풋백 덩크',
    nameEn: 'Putback Dunk',
    difficulty: 2,
    description: '리바운드된 공을 즉시 잡아 꽂는 순발력의 덩크. 포지셔닝이 핵심.',
    controls: 'R + SPACE',
    unlockCondition: '양손 덩크 10회',
    requiredVertical: 75,
    unlocked: false,
    icon: '⚡',
    famous: 'Shaquille O\'Neal의 압도적인 풋백',
    category: 'basic'
  },
  {
    id: 'freethrow_line',
    name: '자유투 라인 덩크',
    nameEn: 'Free Throw Line Dunk',
    difficulty: 5,
    description: '자유투 라인(5.8m)에서 도약하여 덩크. 인간이 할 수 있는 가장 전설적인 덩크.',
    controls: 'F + SPACE',
    unlockCondition: '모든 덩크 해제',
    requiredVertical: 100,
    unlocked: false,
    icon: '👑',
    famous: 'Michael Jordan의 1988 슬램덩크 대회 전설',
    category: 'legendary'
  },
  {
    id: 'eastbay',
    name: '이스트베이 덩크',
    nameEn: 'East Bay Funk Dunk',
    difficulty: 5,
    description: '공을 두 다리 사이로 통과시키며 한 손으로 꽂는 최고 난도 덩크.',
    controls: 'Z + SPACE',
    unlockCondition: '다리 사이 덩크 5회',
    requiredVertical: 95,
    unlocked: false,
    icon: '🌟',
    famous: 'Vince Carter\'s "Air Canada" 덩크 쇼',
    category: 'legendary'
  },
  {
    id: 'double_pump',
    name: '더블 펌프 덩크',
    nameEn: 'Double Pump Dunk',
    difficulty: 4,
    description: '공중에서 두 번 팔을 올렸다 내리며 속이는 모션 후 꽂는 덩크.',
    controls: 'X + SPACE',
    unlockCondition: '토마호크 덩크 10회',
    requiredVertical: 87,
    unlocked: false,
    icon: '🔁',
    famous: 'LeBron James의 체이서 덩크',
    category: 'acrobatic'
  },
  {
    id: 'tip_dunk',
    name: '팁 덩크',
    nameEn: 'Tip Dunk',
    difficulty: 3,
    description: '손끝으로 가볍게 튕기듯 꽂는 핑거롤 스타일 덩크.',
    controls: 'T + SPACE',
    unlockCondition: '원핸드 덩크 20회',
    requiredVertical: 78,
    unlocked: false,
    icon: '☝️',
    famous: 'Kevin Durant의 핑거롤 덩크',
    category: 'basic'
  },
  {
    id: 'chaser',
    name: '체이서 덩크',
    nameEn: 'Chaser Dunk',
    difficulty: 3,
    description: '코너에서 달려오며 베이스라인을 따라 꽂는 스피드 덩크.',
    controls: 'C + SPACE',
    unlockCondition: '양손 덩크 30회',
    requiredVertical: 80,
    unlocked: false,
    icon: '🏃',
    famous: 'Zach LaVine의 닭 날개 덩크',
    category: 'power'
  }
]

export const getDunkById = (id: string) => ALL_DUNKS.find(d => d.id === id)

export const getDunksByCategory = (category: DunkType['category']) =>
  ALL_DUNKS.filter(d => d.category === category)
